version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fitness_app_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  backend:
#    build:
#      context: ./back
#    container_name: fitness-app-backend
#    environment:
#      DATABASE_URL: postgres://fitness_app:fitness_app@postgres:5432/fitness_app
#    depends_on:
#      - postgres
#    ports:
#      - "3001:3001"

#  frontend:
#    build:
#      context: ./front
#    container_name: medium_clone_frontend
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"

volumes:
  postgres_data:
